name: Release manual-pkgs

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Build the .deb package
        run: ./build.sh

      - name: Upload .deb as GitHub Release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/manual-pkgs_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
