name: Test manual-pkgs

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python and run tests
        shell: bash
        run: |
          apt update
          apt install -y python3 python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest pytest-cov
          pytest --cov=get_manual_pkgs --cov-report=term-missing tests