name: Test manual-pkgs

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: debian:12
        steps:
            - name: Install python and dependencies
              run: |
                apt update
                apt install -y python3 python3-pip git
                pip3 install pytest pytest-cov
            
            - name: Checkout repo
              uses: actions/checkout@v3 
            
            - name: Run Tests
              run: pytest --cov=get_manual_pkgs --cov-report=term-missing tests/


            